name = "blog"
main = "src/index.ts"

account_id = "49352e8d5379bd6e7b57ad393d3bc2b9"
workers_dev = true
compatibility_date = "2021-11-06"

[env.development]
name = "blog-development"

[build]
command = "yarn build"
