service: current-auctions

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  versionFunctions: false
  memorySize: 512

functions:
  filterAuctions:
    handler: src/index.filterCurrentAuctions
    events:
      - http:
          path: /
          method: post

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline

package:
  individually: true
